server:
  port: 25000
spring:
  application:
    name: gulimall-seckill
  redis:
    host: 127.0.0.1
    port: 6380
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false